# Overflayer config
server:
  host: quantahedron.biz
  port: 25566
  version: auto

snippet_dirs:
  - path: ./snippets
    writable: true
  - path: ./tmp/local_snippets
    writable: true

_defaults: &defaults
  auth: offline
  load:
    - snippets/navigate.js
    - snippets/eat.js
    - snippets/look.js
    - snippets/follow.js
    - snippets/talk.js
    - snippets/equip.js
    - snippets/gather.js
    - snippets/build.js
    - snippets/inspect.js
    - snippets/defend.js

players:
  - { username: January,   <<: *defaults }
  - { username: February,  <<: *defaults }
  # - { username: March,     <<: *defaults }
  # - { username: April,     <<: *defaults }
  # - { username: May,       <<: *defaults }
  # - { username: June,      <<: *defaults }
  # - { username: July,      <<: *defaults }
  # - { username: August,    <<: *defaults }
  # - { username: September, <<: *defaults }
  # - { username: October,   <<: *defaults }
  # - { username: November,  <<: *defaults }
  # - { username: December,  <<: *defaults }
